# Generated by Django 5.2.7 on 2025-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('', '-- Tanlang --'), ('Академик', 'Akademik'), ('DSc, Профессор', 'DSc, Professor'), ('Профессор', 'Professor'), ('Профессор в.б.', 'Professor v.b.'), ('PhD, Доцент', 'PhD, Dotsent'), ('Доцент', 'Dotsent'), ('Доцент в.б.', 'Dotsent v.b.'), ('Катта ўқитувчи', "Katta o'qituvchi"), ('Ассистент, ўқитувчи', "Assistent, o'qituvchi"), ('Ассистент-стажёр', 'Assistent-stajer')], default='', max_length=50, verbose_name='Ilmiy daraja'),
        ),
    ]
