# Generated by Django 5.2.7 on 2025-11-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF hujjat'), ('video', 'Video'), ('document', 'Hujjat (Word, Excel)'), ('image', 'Rasm'), ('link', 'Havola'), ('archive', 'Arxiv (ZIP, RAR)'), ('other', 'Boshqa')], default='pdf', max_length=20, verbose_name='Turi')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='Fayl')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bytes)')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='Kurs')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
