# Generated by Django 5.2.7 on 2025-11-29 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Ko'p tanlov"), ('true_false', "To'g'ri/Noto'g'ri")], default='single', max_length=20, verbose_name='Savol turi')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name="O'tish bali (%)")),
                ('attempts_allowed', models.PositiveIntegerField(default=1, verbose_name='Urinishlar soni')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Savollarni aralashtirish')),
                ('show_correct_answers', models.BooleanField(default=False, verbose_name="To'g'ri javoblarni ko'rsatish")),
                ('available_from', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('available_until', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ball (%)')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name="To'plangan ball")),
                ('points_possible', models.PositiveIntegerField(default=0, verbose_name='Maksimal ball')),
                ('is_passed', models.BooleanField(null=True, verbose_name="O'tdimi")),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz', verbose_name='Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Test bali')),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Davomat bali')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Topshiriq bali')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Umumiy ball')),
                ('letter_grade', models.CharField(blank=True, max_length=2, verbose_name='Harf baho')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course', verbose_name='Kurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(null=True, verbose_name="To'g'ri")),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assessments.quizattempt', verbose_name='Urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question', verbose_name='Savol')),
                ('selected_answers', models.ManyToManyField(blank=True, to='assessments.answer', verbose_name='Tanlangan javoblar')),
            ],
            options={
                'verbose_name': 'Talaba javobi',
                'verbose_name_plural': 'Talaba javoblari',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
