# Generated by Django 5.2.7 on 2025-11-29 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish'), ('view_course', "Kurs ko'rish"), ('enroll_course', 'Kursga yozilish'), ('view_lesson', "Dars ko'rish"), ('complete_lesson', 'Dars tugatish'), ('start_quiz', 'Test boshlash'), ('complete_quiz', 'Test tugatish')], max_length=50, verbose_name='Faollik turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='courses.course', verbose_name='Kurs')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='courses.lesson', verbose_name='Dars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Faollik',
                'verbose_name_plural': 'Faolliklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
